[project]
name = "py-currency"
description = "Currency classes to work with monetary values"
version = "0.1"
authors = [{ name = "Vítor dos Santos Araujo", email = "vitoraraujo@tuta.com" }]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["dependencies"]
requires-python = ">=3.11"

[project.urls]
Documentation = "https://vsbits.net/currency/"
Repository = "https://github.com/vsbits/currency"
Issues = "https://github.com/vsbits/currency/issues"

[project.optional-dependencies]
tests = ["flake8", "mypy", "pytest", "pytest-cov", "pandas"]

[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.ruff]
line-length = 79
