name: Unit tests

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Lint with flake8
      run: |
        flake8 src --exit-zero --max-complexity=10 --max-line-length=80 --statistics
    
    - name: Lint with mypy
      run: |
        mypy src

    - name: Test with pytest
      run: |
        pytest --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
